version: '3.8'

services:
  mysql1:
    image: mysql/mysql-server:8.0
    container_name: mysql1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - innodb-cluster
    ports:
      - "3307:3306"
    volumes:
      - mysql1-data:/var/lib/mysql

  mysql2:
    image: mysql/mysql-server:8.0
    container_name: mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser docker ps -a
      
      MYSQL_PASSWORD: mypassword
    networks:
      - innodb-cluster
    ports:
      - "3308:3306"
    volumes:
      - mysql2-data:/var/lib/mysql

  mysql3:
    image: mysql/mysql-server:8.0
    container_name: mysql3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - innodb-cluster
    ports:
      - "3309:3306"
    volumes:
      - mysql3-data:/var/lib/mysql

  mysql-shell:
    image: mysql:8.0
    container_name: mysql-shell
    networks:
      - innodb-cluster
    entrypoint: ["tail", "-f", "/dev/null"] # Keep the container running
    depends_on:
      - mysql1
      - mysql2
      - mysql3

networks:
  innodb-cluster:

volumes:
  mysql1-data:
  mysql2-data:
  mysql3-data:
